In [26]:
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine

# 1. Load:
df = pd.read_csv(r"C:\Users\Gowsalya\SuperMarket_Cleaned.csv")
print(f"Loaded shape: {df.shape}")

Loaded shape: (1000, 28)

In [27]:
# 2. Create database:
conn = mysql.connector.connect(host="localhost", user="root", password="2005")
cursor = conn.cursor()
cursor.execute("CREATE DATABASE IF NOT EXISTS supermarket_db")
cursor.execute("USE supermarket_db")
cursor.close()
conn.close()

# 3. Load data into MySQL table
engine = create_engine("mysql+mysqlconnector://root:2005@localhost/supermarket_db")
df.to_sql(name="supermarket_sales", con=engine, if_exists="replace", index=False)
print("Data successfully loaded into MySQL table: supermarket_sales")

Data successfully loaded into MySQL table: supermarket_sales

In [28]:
##1.Total Orders
query = """
SELECT COUNT(*) AS Total_Orders FROM supermarket_sales;
"""
result = pd.read_sql(query, engine)
result

   Total_Orders
0          1000

In [29]:
##2.Overall Sales, Cost, Profit Summary
query = """
SELECT 
    ROUND(SUM(Sales),2) AS Total_Sales,
    ROUND(SUM(Cost),2) AS Total_Cost,
    ROUND(SUM(Profit),2) AS Total_Profit,
    COUNT(*) AS Total_Orders
FROM supermarket_sales;
"""
result = pd.read_sql(query, engine)
result

   Total_Sales  Total_Cost  Total_Profit  Total_Orders
0   2027774.05  1471703.09     556070.96          1000

In [30]:
##3.Region-wise Sales & Profit
query = """
SELECT Region, 
    ROUND(SUM(Sales),2) AS Total_Sales, 
    ROUND(SUM(Profit),2) AS Total_Profit,
    COUNT(*) AS Orders
FROM supermarket_sales
GROUP BY Region
ORDER BY Total_Sales DESC;
"""
result = pd.read_sql(query, engine)
result

  Region  Total_Sales  Total_Profit  Orders
0  South   1109182.40     303504.29     544
1   West    549934.65     151085.12     271
2   East    192978.75      51684.88      96
3  North    175678.25      49796.67      89

In [31]:
##4.Top 10 Products by Sales

query = """
SELECT Product_Name, 
    ROUND(SUM(Sales),2) AS Total_Sales,
    SUM(Quantity) AS Total_Quantity
FROM supermarket_sales
GROUP BY Product_Name
ORDER BY Total_Sales DESC
LIMIT 10;
"""
result = pd.read_sql(query, engine)
result

    Product_Name  Total_Sales  Total_Quantity
0      Detergent    111537.50           275.0
1     Chips Pack    106511.65           256.0
2      Apple 1Kg    104579.10           279.0
3  Biscuits Pack     98281.10           240.0
4        Namkeen     94507.50           226.0
5      Soap Pack     94233.15           265.0
6   Banana Dozen     92660.80           290.0
7    Yogurt Pack     91862.30           267.0
8     Soft Drink     86344.10           220.0
9        Milk 1L     80860.55           213.0

In [32]:
##5.Category-wise Sales & Profit Margin
query = """
SELECT Product_Category, 
    ROUND(SUM(Sales),2) AS Total_Sales, 
    ROUND(SUM(Profit),2) AS Total_Profit,
    ROUND(AVG(`Profit_Margin_%`),2) AS Avg_Margin_Percent
FROM supermarket_sales
GROUP BY Product_Category
ORDER BY Total_Sales DESC;
"""
result = pd.read_sql(query, engine)
result

  Product_Category  Total_Sales  Total_Profit  Avg_Margin_Percent
0           Snacks    299300.25      85640.64               28.23
1        Beverages    293671.10      82058.02               27.28
2           Fruits    268143.55      70897.14               26.96
3        Household    268009.35      70601.23               27.09
4    Personal Care    246287.30      67552.46               27.29
5          Grocery    239565.65      62641.35               26.61
6            Dairy    233608.25      67037.48               28.45
7       Vegetables    179188.60      49642.64               27.66

In [33]:
##6.Monthly Sales Trend

query = """
SELECT Order_Year, Order_Month, Order_Month_Name,
    ROUND(SUM(Sales),2) AS Monthly_Sales
FROM supermarket_sales
GROUP BY Order_Year, Order_Month, Order_Month_Name
ORDER BY Order_Year, Order_Month;
"""
result = pd.read_sql(query, engine)
result

    Order_Year  Order_Month Order_Month_Name  Monthly_Sales
0         2024            1              Jan       66725.20
1         2024            2              Feb       59478.35
2         2024            3              Mar       86354.90
3         2024            4              Apr      104278.05
4         2024            5              May       65537.45
5         2024            6              Jun      110266.85
6         2024            7              Jul       90179.20
7         2024            8              Aug       70209.80
8         2024            9              Sep       73667.75
9         2024           10              Oct       57515.70
10        2024           11              Nov       99301.55
11        2024           12              Dec       91813.15
12        2025            1              Jan       73778.40
13        2025            2              Feb      107223.75
14        2025            3              Mar       84455.80
15        2025            4              Apr       80411.15
16        2025            5              May      111527.45
17        2025            6              Jun       66971.70
18        2025            7              Jul       62568.65
19        2025            8              Aug       95537.25
20        2025            9              Sep       84509.70
21        2025           10              Oct      108633.85
22        2025           11              Nov       82910.70
23        2025           12              Dec       93917.70

In [34]:
##7. Payment Mode Distribution

query = """
SELECT Payment_Mode, 
    COUNT(*) AS Order_Count, 
    ROUND(SUM(Sales),2) AS Total_Sales
FROM supermarket_sales
GROUP BY Payment_Mode
ORDER BY Total_Sales DESC;
"""
result = pd.read_sql(query, engine)
result

  Payment_Mode  Order_Count  Total_Sales
0         Cash          353    765369.45
1          UPI          322    639056.25
2         Card          325    623348.35

In [35]:
##8.Discount Impact on Profit Margin

query = """
SELECT Discount_Percent, 
    COUNT(*) AS Orders,
    ROUND(AVG(`Profit_Margin_%`),2) AS Avg_Margin_Percent
FROM supermarket_sales
GROUP BY Discount_Percent
ORDER BY Discount_Percent;
"""
result = pd.read_sql(query, engine)
result

   Discount_Percent  Orders  Avg_Margin_Percent
0                 0     219               27.42
1                 5     195               27.15
2                10     195               28.01
3                15     202               27.15
4                20     189               27.44

In [36]:
##9.Weekday-wise Sales Pattern

query = """
SELECT Order_Weekday, 
    COUNT(*) AS Orders, 
    ROUND(SUM(Sales),2) AS Total_Sales
FROM supermarket_sales
GROUP BY Order_Weekday
ORDER BY Total_Sales DESC;
"""
result = pd.read_sql(query, engine)
result

  Order_Weekday  Orders  Total_Sales
0        Sunday     160    321327.40
1     Wednesday     138    315657.70
2      Thursday     147    301420.10
3        Friday     146    278789.20
4      Saturday     138    271700.35
5       Tuesday     133    271237.65
6        Monday     138    267641.65

In [37]:
##10.Top 10 Customers by Total Spend

query = """
SELECT Customer_ID, Customer_Name, 
    ROUND(SUM(Sales),2) AS Total_Spend,
    COUNT(*) AS Orders
FROM supermarket_sales
GROUP BY Customer_ID, Customer_Name
ORDER BY Total_Spend DESC
LIMIT 10;
"""
result = pd.read_sql(query, engine)
result

  Customer_ID   Customer_Name  Total_Spend  Orders
0       C0790  Karthik Sharma       8000.0       1
1       C0684     Pooja Verma       7510.0       1
2       C0494     Vijay Reddy       7334.0       1
3       C0282      Suresh Das       7150.0       1
4       C0130     Vijay Menon       7029.0       1
5       C0371        Ravi Rao       7002.0       1
6       C0237   Dinesh Joseph       6992.0       1
7       C0374     Sneha Kumar       6804.0       1
8       C0134     Rahul Patel       6688.0       1
9       C0072     Ravi Sharma       6669.0       1